language: cpp
compiler: cl
os: windows
script:
- source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
- mkdir build
- cd build
- cmake -G "NMake Makefiles" ..
- nmake all
- 7z a Shear3D.zip Shear3D
- ls
deploy:
  provider: releases
  api_key:
    secure: S0YFrX2/n2s+5ohPVVuWTlZyLC1vbKf2uLwPYr2XePvxS1l16rp8VeGM0K8gm5uUu1ttOcn/zBEBfJFoqYhZPtuqLe+EW+4+LJBbpSfjt288WWF9Xg5OBctmyxrrxDbjECUOHddNOKA+8Gv+i8r7G8i72urY92Xxl7EDlf1bAWXPLGxWkTtAtHt30eDRqpsYVktCWYcjJRPBf7ISAmhyFjjVgzKxhUL4RACYrKgfh3sXsuaM4fbjkwp1ib0ttiuhUqudzaUM9SOYVWsDEMfYvTBPwcmnZ7NK3sbKYV1PdmdUClT2uL0PE3Ko1fn5U1SUNs+K/vRnfmAjIakDTWi8VCamk64me2w4hCMF27L2X7jEjrXmwcSMQGUx4r7cHhxpjh7Xk6Jnd8obO4vBMl8i2JXYoORNoOSIxW9pkxe8Ww04AL7BEceUHxWmeAtnNXhUdWacGOW+4lJO6T5U3/AftzwkxiQftRwg3tEooStHd5yhuwXa1FQ6ri3MbkGwQekE1nHag/VInhsmXYmh18+CQ9pzSCyxnkxN6TkkKpMQ1u2bgE2B5y4xzyq20KmhMMLxxloftZO5VY8KIH4/0HVcPo9Fxx43hV2y60gwm6PeLpQkICcL+6wRSjq61gLj5jNDZR9k2pdT1bz0m6T4qx2m01vopW868PexM/0UdVipBl8=
  file: Shear3D.zip
  skip_cleanup: true
  on:
    tags: true
