language: cpp
compiler: clang
os: windows
script:
    - source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
    - mkdir build
    - cd build
    - cmake ..
    - ls
    - devenv Shear3D.sln /build

# before_install:
