language: cpp
compiler: cl
os: windows
env:
    - CMAKE_CXX_COMPILER="cl.exe"
    - CMAKE_C_COMPILER="cl.exe"
script:
    - source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" ..
    - nmake all
    - ls
deploy:
    provider: releases
    api_key: "7f61fd49743b39c7438cdf441c01a501094d86f6"
    file: "build/Shear3D/Shear3D.exe"
    skip_cleanup: true
    on:
        tags: true
# before_install:
