language: cpp
compiler: clang
os: windows
script:
    - source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" ..
    - ls
    - nmake

# before_install:
