language: cpp
compiler: clang
os: windows
script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" ..
    - ls
    - MSBuild.exe Shear3D.proj -property:Configuration=release

# before_install:
