language: cpp
compiler: cl
os: windows
script:
- source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
- mkdir build
- cd build
- cmake -G "NMake Makefiles" ..
- nmake all
- 7z a Shear3D.zip Shear3D
- ls
deploy:
  provider: releases
  user: potion@live.cn
  password:
    secure: PjGki4n6TJYuhnWqI6kRjwd+izaoOHkvir3dUWYIhmFHhVZd5A71ZTbJJPYHH3q55DDabs3WFT/Op4vG2MZoRI014gLmDKKnRtGFgheadYatEnMJfRQsRIRTOPrudjjlhFr2iu0vYpukJxr5tCt369bNBUuRQvmQBRpKRtFQRFKgbIOJRzG/GMf3r5gtfh2JyQVlMfe6OPSPhLmoL+wR1TbJrXbRQ0++If1s2EWbbSNqMO1GHcJ1EI3697+gMWRom5peA8jst9GQ3+BB1YYFL5JbWLRuE3O1fCsgNmMWRSl+M//5PLP/9XodZt7ocI+w9TC5eCOLcrLnrR2ohVRshTFRoPq4m2lpuadu4KROWzzGns96t7DqM1lY19QkBl1jYFt8YmD5gD4N5NsocEtjM+tGC5K8n8T+Gl6tRj+Nua42BHWJa9OVnN27q+hZrU3IhuHIUobhmM9FESPQvsiE/lRDMxoCy2Amv/Tr3+hGWiLpnt5jF9GIddQlYdM6uwRC/WGDARiFsJa65ZVogp+zwEgohD6tLcxzbP4w+G0L5DBELev+z2vbrk4icwYOEjnR0PswjTsHyuVcqsi+Mtg0y/69k8GApdUiKQBf6Fm+dyt1u/u5k1ieL6Ycoto8sBCB2Zh2LIZ8/3aEcHPhcU4jZj3JCoEh74ViBx6FlXTv1Og=
  file: build/Shear3D.zip
  skip_cleanup: true
  on:
    tags: true
