language: cpp
compiler: cl
os: windows
env:
    - CMAKE_CXX_COMPILER="cl.exe"
    - CMAKE_C_COMPILER="cl.exe"
script:
    - source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" ..
    - ls
    - nmake all

# before_install:
