language: cpp
compiler: cl
os: windows
script:
- source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
- mkdir build
- cd build
- cmake -G "NMake Makefiles" ..
- nmake all
- 7z a Shear3D.zip Shear3D
- ls
deploy:
  provider: releases
  api_key:
    secure: EgBquIqxs/OuAA7gQ2tsgAai0lXVO3BcuT5brem4Z9luHOYrLWdCwXKEH+gKLhwQJ0i8r4DHz1q6k/2ZrSonCqHSGuNy/eNvbgpLngcpZwEY7CxfbM2itoyS4Fb6YG8oyL3ZQnE/LKSE96Eas5ekknrFL/6AiRLMslxsC3wKUfYaGK6KQz3u9ii2mjRrjJd7znPckXn3S4q3lmh13cLYavUmsTyH3Qs7K4vmT3eRA2dKMdEJMPnYGB+ktspcjFO3HckSE+Q2d+WAPN1ndEBh8LVAZsZnwxMNoqU0nvHuOSsGO3mSD2ZRsxohvnKguIJHQF7C3q1lVpl2MKQfMm+X+ZO13/CBSX66wDzVK32BZ2s7Eaxt+S2nAqFLShnPM/zjKmuICIQ0bVgBPnBrc5Wy8cZJVcZ877cnJzFnjp1O2Z+UOas8MNbASbW2uElkUTVzBUZAGLwnvw3e6fe1+7lsXHJGZFQ/A/twGWtn2HSqiILYrV/3QCxzDCWbdDussmKGAQoDxY/8llkPDdRs1Hhkd6JoYUEC+23TnV+GjfrxXZvHlUD6sgJgp/vtvNhOoomQ/dyw3eQL6CRhHv6OtQPYLlq/6uYFkA9ivwOteHD/rH6rPZpqjLj+vINcGfAgI4U0ZCC96xZeoWkrd1FJFDHeWEp4iWkHCOZM1/fIsFVSH+g=
  file: build/Shear3D.zip
  on:
    tags: true

