language: cpp
compiler: cl
os: windows
script:
- source ./run_command_and_apply_environment_differences.sh "call vcvars64_vs2017.bat"
- mkdir build
- cd build
- cmake -G "NMake Makefiles" ..
- nmake all
- 7z a Shear3D.zip Shear3D
- ls
deploy:
  provider: releases
  user: 42yeah
  password:
    secure: hI4uJTSQFThCYBH7fTgnWsQLAVsl0uTqGys0+/GoCxSi5krzKs3z7BacrCNs4h7kTIignzka6IFZBRQFQfI1Y/AeaLwecQL3GaQHM10tPd1i1ipDQ1c6FbbCiRHVV29Dozfhg2LKkcTsvqpHsJdDPLno0GfXWjGNcsH6MNVP7T3it/vXAj3CyMGJKC1cmXrWUc2HT0yVkd1fO8zetacZWb9wfv2RWp3Q43Hl6+jOYrG04QycCwDfIHgdbVWwmKU70mTGc6TPAKDiaeA0UwrURNRZbDz/m+S51CCUSqXr4qgqRUizZ2IWWgsLN5yHI0Hzk1FsS1OXh42qzgi6CNeeSgR+S08RnWvbYqz6WGhsLravlbgD1fw8bGBBqUt3LqJquLkYLeO/XM9HDhKqDBjQJGkrtB1yUEWOCWfEwuYOWCQeABXJoDgeUuBt8purzeF81l1i9cOiwlqA20JFqwhfr3TNoj95zYTw4ACz7pgrnE4mlqaHsebmxcdrluorU8lVEJf4L4aJ/PRQFRxN4Hfue+CBd87hlqWXWl7pNifoNZ/Xo9QWnsVRh8WPUDydenAPo7ebxKU6XW1ztdjAQzoT+JNCeMF8MiSSw5iDng8QzhOEiwLwaWBgmeKjhpgda8uUTRaP1Ll4R6dzvPY2yPMfSRYhckJQil5tmKCGS1aNsys=
  file: build/Shear3D.zip
  skip_cleanup: true
  on:
    tags: true
